package org.ulman.simulator;

public class SimulationConfig {
	public boolean PREPEND_HINT_LABELS = Simulator.PREPEND_HINT_LABELS;
	public boolean COLLECT_INTERNAL_DATA = Simulator.COLLECT_INTERNAL_DATA;
	public boolean VERBOSE_AGENT_DEBUG = Simulator.VERBOSE_AGENT_DEBUG;
	public boolean VERBOSE_SIMULATOR_DEBUG = Simulator.VERBOSE_SIMULATOR_DEBUG;
	public double AGENT_SEARCH_RADIUS = Simulator.AGENT_SEARCH_RADIUS;
	public double AGENT_MIN_DISTANCE_TO_ANOTHER_AGENT = Simulator.AGENT_MIN_DISTANCE_TO_ANOTHER_AGENT;
	public double AGENT_USUAL_STEP_SIZE = Simulator.AGENT_USUAL_STEP_SIZE;
	public int AGENT_NUMBER_OF_ATTEMPTS_TO_MAKE_A_MOVE = Simulator.AGENT_NUMBER_OF_ATTEMPTS_TO_MAKE_A_MOVE;
	public boolean AGENT_DO_2D_MOVES_ONLY = Simulator.AGENT_DO_2D_MOVES_ONLY;
	public int AGENT_AVERAGE_LIFESPAN_BEFORE_DIVISION = Simulator.AGENT_AVERAGE_LIFESPAN_BEFORE_DIVISION;
	public int AGENT_MAX_LIFESPAN_AND_DIES_AFTER = Simulator.AGENT_MAX_LIFESPAN_AND_DIES_AFTER;
	public int AGENT_MAX_DENSITY_TO_ENABLE_DIVISION = Simulator.AGENT_MAX_DENSITY_TO_ENABLE_DIVISION;
	public double AGENT_MAX_VARIABILITY_FROM_A_PERPENDICULAR_DIVISION_PLANE = Simulator.AGENT_MAX_VARIABILITY_FROM_A_PERPENDICULAR_DIVISION_PLANE;
	public double MASTODON_SPOT_RADIUS = Simulator.MASTODON_SPOT_RADIUS;
	public boolean MASTODON_CENTER_SPOT = Simulator.MASTODON_CENTER_SPOT;
}
